### ISSUE TITLE
iphoneXS扫码用Safari下载慢:ArchLinux用konsole运行ProjectSend-linux-amd64拖拽file1.aac

### ISSUE THREAD

**Issue by huntagain2008** [44670/ProjectSend#3]
在公司用台式机运行ProjectSend。20MB的文件通过iphoneXS的Safari下载要几分钟。台式机浏览器用的Chromium版本 99.0.4844.84（正式版本）Arch Linux （64 位）

**Comment by 44670** [comment]
会不会是网络有限制？

**Comment by huntagain2008** [comment]
可能是公司的无线AP距离太远，在门外大厅而不是在办公室。准备试下其他python传文件的工具试试。

**Comment by 44670** [comment]
speedtest.net测一下看看

**Comment by huntagain2008** [comment]
用iphoneXS打开speedtest.net点击GO得到DOWNLOAD Mbps 6.20 Ping 7ms

**Comment by huntagain2008** [comment]
![image](https://user-images.githubusercontent.com/17734974/160318748-919301da-086c-41b6-b9ab-74fdd620b97a.png)
忽然发现VLC有WIFI共享文件的功能。20MB的文件2秒就传过去了。
