### ISSUE TITLE
能指定监听的IP地址吗

### ISSUE THREAD

**Issue by xtay573269555** [44670/ProjectSend#4]
能指定监听的IP地址吗？

之前一直用这个软件，用来在电脑和手机之间传输文件或text，挺方便的。
但最近重装windows后，每次启动这个软件，仅在 127.0.0.1 上监听。也没有找到设置监听IP的参数？

电脑上有多个网卡，有线和wifi，还在 virtuabox 的虚报网卡。系统是 Windows 8.1。

**Comment by 44670** [comment]
默认服务端是监听0.0.0.0，也就是所有的IPv4地址。

网页上显示的是IP，是默认Internet路由所在的网卡对应的IP，其实所有本机IPv4都可以访问的。

如果不能访问的话，可能是Windows防火墙的问题。

**Comment by xtay573269555** [comment]
确实，显示的只是其中一个IP地址，使用其它IP地址去访问也是可以的。
谢谢！
